---
title: "Traits prediction (Peter)"
author: "tnauss"
date: "2 März 2018"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gpm)
library(reshape2)
traits = read.table("C:/Users/tnauss/permanent/plygrnd/exploratorien/data/manning/cwm_exploratories_1.csv",
                    header = TRUE, sep = ",", dec = ".")
traits = traits[traits$Year == 2015, -c(1, 3)]
traits$EP_PlotID = as.character(traits$EP_PlotID)
traits$EP_PlotID[nchar(traits$EP_PlotID) == 4] = paste0(substr(traits$EP_PlotID[nchar(traits$EP_PlotID) == 4], 1, 3), "0", substr(traits$EP_PlotID[nchar(traits$EP_PlotID) == 4], 4, 4))

re_mgpm = readRDS(file = paste0("C:/Users/tnauss/permanent/plygrnd/exploratorien/data/manning/cmw_mgpm_model.rds"))
lui_mgpm = readRDS(file = paste0("C:/Users/tnauss/permanent/plygrnd/exploratorien/data/manning/cmw_mgpm_model_lui.rds"))


var_imp <- compVarImp(re_mgpm[[1]]@model[[1]], scale = FALSE)
var_imp_scale <- compVarImp(re_mgpm[[1]]@model[[1]], scale = TRUE)
var_imp_plot <- plotVarImp(var_imp)
var_imp_heat <- plotVarImpHeatmap(var_imp_scale, xlab = "Species", ylab = "Band")



#### Some stats
# Model CV
mgpm_model_stats = lapply(names(re_mgpm), function(be){
  rspns = lapply(seq(length(re_mgpm[[be]]@model$pls_rfe)), function(r){
    smpls = lapply(seq(length(r)), function(s){
      data.frame(belc = be, 
                 model_response = re_mgpm[[be]]@model$pls_rfe[[r]][[s]]$response,
                 re_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$results[re_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$bestTune[,1],],
                 model_rmse_norm = re_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$results$RMSE[re_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$bestTune[,1]] /
                   mean(re_mgpm[[be]]@model$pls_rfe[[r]][[s]]$training$RESPONSE))
      
    })
    do.call("rbind", smpls)
  })
  do.call("rbind", rspns)
})
mgpm_model_stats = do.call("rbind", mgpm_model_stats)
names(mgpm_model_stats)[4:7] = paste0("model_", names(mgpm_model_stats)[4:7])

# Independent prediction
mgpm_stats = lapply(names(re_mgpm), function(be){
  var_imp = compVarImp(re_mgpm[[be]]@model$pls_rfe, scale = FALSE)
  var_imp_scale = compVarImp(re_mgpm[[be]]@model$pls_rfe, scale = TRUE)
  var_imp_plot = plotVarImp(var_imp)
  var_imp_heat = plotVarImpHeatmap(var_imp_scale, xlab = "Species", ylab = "Band")
  tstat = compRegrTests(re_mgpm[[be]]@model$pls_rfe, details = TRUE)
  tstat$belc = substr(tstat$model_selector, 1, 3)
  lmod = lm(testing_predicted ~ testing_response, data = tstat)
  rsqrd = summary(lmod)$r.squared
  tstat_cmpl = list(var_imp = var_imp, var_imp_scale = var_imp_scale, 
                    var_imp_plot = var_imp_plot, var_imp_heat = var_imp_heat,
                    tstat = tstat, lmod = lmod, rsqrd = rsqrd)
  return(tstat_cmpl)
})
names(mgpm_stats) = names(re_mgpm)

mgpm_stats_tstat = do.call("rbind", lapply(seq(3), function(i){mgpm_stats[[i]]$tstat}))
mgpm_stats_tstat = merge(mgpm_stats_tstat, mgpm_model_stats, by = c("belc", "model_response"))

mgpm_stats_tstat_rmse = data.frame(belc = mgpm_stats_tstat$belc,
                                   model_response = mgpm_stats_tstat$model_response,
                                   # indp_rmse = mgpm_stats_tstat$rmse, 
                                   # model_rmse = mgpm_stats_tstat$model_RMSE,
                                   indp_rmse_norm = mgpm_stats_tstat$rmse_norm,
                                   model_rmse_norm = mgpm_stats_tstat$model_rmse_norm)
mgpm_stats_tstat_rmse = melt(mgpm_stats_tstat_rmse, idvar = c("belc", "model_response"))


var_imp <- compVarImp(lui_mgpm[[1]]@model[[1]], scale = FALSE)
var_imp_scale <- compVarImp(lui_mgpm[[1]]@model[[1]], scale = TRUE)
var_imp_plot <- plotVarImp(var_imp)
var_imp_heat <- plotVarImpHeatmap(var_imp_scale, xlab = "Species", ylab = "Band")

#### Some stats
# Model CV
mgpm_model_stats = lapply(names(lui_mgpm), function(be){
  rspns = lapply(seq(length(lui_mgpm[[be]]@model$pls_rfe)), function(r){
    smpls = lapply(seq(length(r)), function(s){
      data.frame(belc = be, 
                 model_response = lui_mgpm[[be]]@model$pls_rfe[[r]][[s]]$response,
                 lui_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$results[lui_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$bestTune[,1],],
                 model_rmse_norm = lui_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$results$RMSE[lui_mgpm[[be]]@model$pls_rfe[[r]][[s]]$model$fit$bestTune[,1]] /
                   mean(lui_mgpm[[be]]@model$pls_rfe[[r]][[s]]$training$RESPONSE))
      
    })
    do.call("rbind", smpls)
  })
  do.call("rbind", rspns)
})
mgpm_model_stats = do.call("rbind", mgpm_model_stats)
names(mgpm_model_stats)[4:7] = paste0("model_", names(mgpm_model_stats)[4:7])

# Independent prediction
mgpm_stats = lapply(names(lui_mgpm), function(be){
  var_imp = compVarImp(lui_mgpm[[be]]@model$pls_rfe, scale = FALSE)
  var_imp_scale = compVarImp(lui_mgpm[[be]]@model$pls_rfe, scale = TRUE)
  var_imp_plot = plotVarImp(var_imp)
  var_imp_heat = plotVarImpHeatmap(var_imp_scale, xlab = "Species", ylab = "Band")
  tstat = compRegrTests(lui_mgpm[[be]]@model$pls_rfe, details = TRUE)
  tstat$belc = substr(tstat$model_selector, 1, 3)
  lmod = lm(testing_predicted ~ testing_response, data = tstat)
  rsqrd = summary(lmod)$r.squared
  tstat_cmpl = list(var_imp = var_imp, var_imp_scale = var_imp_scale, 
                    var_imp_plot = var_imp_plot, var_imp_heat = var_imp_heat,
                    tstat = tstat, lmod = lmod, rsqrd = rsqrd)
  return(tstat_cmpl)
})
names(mgpm_stats) = names(lui_mgpm)

mgpm_stats_tstat = do.call("rbind", lapply(seq(3), function(i){mgpm_stats[[i]]$tstat}))
mgpm_stats_tstat = merge(mgpm_stats_tstat, mgpm_model_stats, by = c("belc", "model_response"))

mgpm_stats_tstat_rmse = data.frame(belc = mgpm_stats_tstat$belc,
                                   model_response = mgpm_stats_tstat$model_response,
                                   # indp_rmse = mgpm_stats_tstat$rmse, 
                                   # model_rmse = mgpm_stats_tstat$model_RMSE,
                                   indp_rmse = mgpm_stats_tstat$rmse_norm,
                                   model_rmse = mgpm_stats_tstat$model_rmse_norm)
mgpm_stats_tstat_rmse = melt(mgpm_stats_tstat_rmse, idvar = c("belc", "model_response"))

mresps = unique(mgpm_stats_tstat$model_response)
q75 = lapply(mresps, function(r){
  data.frame(response = r,
             quant_075 = quantile(mgpm_stats_tstat$rmse_norm[mgpm_stats_tstat$model_response == r])[4])
})
q75 = do.call("rbind", q75)

ok = q75$response[q75$quant_075 <= 0.5]


```

## Prediction performance using RapidEye or LUI
```{r, echo = FALSE}


```



```{r, echo = FALSE}


```



```{r, echo = FALSE}


```



```{r, echo = FALSE}


```



```{r, echo = FALSE}


```



```{r, echo = FALSE}


```


```{r, echo = FALSE}


```